// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package persistence

import (
	"github.com/eldius/onedrive-client/internal/configs"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewDB() *gorm.DB {
	string2 := configs.GetDBFilePath()
	gormDB := GetDB(string2)
	return gormDB
}
