// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecase

import (
	"github.com/eldius/onedrive-client/client"
	"github.com/eldius/onedrive-client/internal/persistence"
)

// Injectors from wire.go:

func NewFileUpload(clientClient client.Client) *FileUploadUseCase {
	db := persistence.NewDB()
	authRepository := persistence.NewAuthRepository(db)
	fileUploadUseCase := newFileUploadUseCase(clientClient, authRepository)
	return fileUploadUseCase
}

func NewListFilesUseCase(clientClient client.Client) *ListFilesUseCase {
	db := persistence.NewDB()
	authRepository := persistence.NewAuthRepository(db)
	listFilesUseCase := newListFilesUseCase(authRepository)
	return listFilesUseCase
}

func NewDriveAddUseUseCase(clientClient client.Client) *DriveAddUseUseCase {
	db := persistence.NewDB()
	authRepository := persistence.NewAuthRepository(db)
	driveAddUseUseCase := newDriveAddUseCase(clientClient, authRepository)
	return driveAddUseUseCase
}
